# Sử dụng phiên bản 3.8 của Docker Compose
version: "3.8"

# Định nghĩa các services (dịch vụ)
services:
  # Dịch vụ cho ứng dụng React (frontend)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_drive_organizer_app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks: # Thêm vào mạng app_net
      - app_net

  # Dịch vụ cho máy chủ Python (backend)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: python_ai_backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      # Sử dụng biến từ file .env
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks: # Thêm vào mạng app_net
      - app_net

  # Dịch vụ mới cho database PostgreSQL
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      # Sử dụng biến từ file .env
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: # Thêm vào mạng app_net
      - app_net

# Định nghĩa mạng tùy chỉnh
networks:
  app_net:
    driver: bridge

# Định nghĩa volume để lưu trữ dữ liệu database một cách bền vững
volumes:
  postgres_data:
